// // try{
// //     console.log(x);
// // }
// // catch(error)
// // {
// //     console.log(error)
// // }

// try{
//     a=[1,2,34,5,6,7]
//     console.log(a);
//     console.log(b)
// }
// catch(error)
// {
//     console.log("There is error which shows "+error)
// }



try{
  
    console.log("we are inside the try block")
}
catch(error)
{
    console.log(error)
}